src/sa.c
src/test.c
src/test.h

net: add a test for net_resolve_address()

sa: add support for interface suffix for IPv6ll

---

src/sipsess.c

related to https://github.com/baresip/re/pull/135

outgoing calls early callid

---

src/ice.c

enum ice_mode will be removed, support full mode only

ice: full mode only

---

src/sipreg.c

relates to: https://github.com/baresip/re/pull/198

sip: add optional TCP source port

---

src/aubuf.c
src/list.c

relates to: https://github.com/baresip/re/pull/209

aubuf insert auframes sorted

---

src/main.c
src/test.c
src/test.h
src/tmr.c

test: rename network to integration and move tmr tests

---

src/rtp.c
src/test.c
src/test.h

Author: phancke@nvidia.com
https://github.com/baresip/re/pull/264

add transport-cc rtcp feedback support

---

src/fmt.c
src/test.c
src/test.h

- fmt: add test_fmt_gmtime
- fmt: add test_fmt_timestamp

uag: add timestamps to SIP trace

---

src/sa.c

fix for https://github.com/baresip/retest/issues/98

sa: fix valgrind warning on 32-bits

---

src/aubuf.c

relates to: https://github.com/baresip/rem/pull/75

aubuf: prevent faulty timestamps

---

CMakeLists.txt

cmake: bump minimum to 3.10

---

src/dns.c

test new api dnsc_getaddrinfo_enabled

dns, http: add dnsc_getaddrinfo_enabled. prevent reset of getaddrinfo enabled

---

src/rtp.c

This updates RTP tests for compatibility with this PR:
https://github.com/baresip/re/pull/418

rtp: Improve media synchronization

---

src/crc32.c

Add a crc32 wrapper agnostic to CRC32 backend

crc32: add re wrapper

---

src/http.c
src/test.c
src/test.h

Support run specific integration test
Add test for http using local dns server

Support run specific integration test and add http with local dnssrv

---

src/ice.c

depends on: https://github.com/baresip/re/pull/589

ice: local candidate policy config

---

src/test.c

refs https://github.com/baresip/re/pull/597#issuecomment-1320929709

test: replace freopen with dup/dup2

---

.github/workflows/all.yml
.github/workflows/build.yml
.github/workflows/ccheck.yml

fixes valgrind openssl 3 and dwarf-5 issues refs #160

ci: use ubuntu-20.04

---

src/remain.c

https://github.com/baresip/re/pull/615

main: allow for init twice

---

.github/workflows/build.yml
src/mock/turnsrv.c
src/test.c
src/test.h
src/turn.c

Ref https://github.com/baresip/baresip/discussions/2445

turn: add rx thread and refresh test handling
