src/jbuf.c, src/test.c, src/test.h
- Fixes build since the jbuf_alloc() parameters had been extended by wish size
and ptime.
- Adds tests for wish size.
- Fix valgrind warnings "Conditional jump depends on uninitialized value".
Related to: https://github.com/baresip/re/pull/41
=> Adaptive jbuf

src/http.c
In libre the peer verification was added for HTTP clients. Thus the client
verifies the server certificate chain of trust and hostname (SNI). In the test
the chain of trust verification failed.
=> HTTP SNI check

src/jbuf.c
@cspiel1 this fixes the race condition on macos (1/10 Tests fails). Seems the sys_msleep is not needed. Do you agree?
=> jbuf/test_jbuf_adaptive: remove sys_msleep (fixes macOS fails)

src/sys.c, src/test.c, src/test.h, src/tls.c
Negativ testcases where cafile and capath are wrong.
Testcases for fs_isdir
=> tls: more generic function to set cafile and capath

src/tmr.c
The variable `diff` was zero on travis. Could reproduce on my `AMD Ryzen 3 3100 4-Core Processor`
=> tmr: fix test_tmr_jiffies_usec for fast machines

src/tls.c
Should increase the test coverage for function tls_get_subject(). Libre pr: https://github.com/baresip/re/pull/94
=> tls: add test checks for tls_get_subject()

src/sipsess.c, src/test.c, src/test.h
Testcase of the new redirect callback function handler.
Depends on PR [re#111](https://github.com/baresip/re/pull/111)
=> SIP redirect callbackfunction

src/sa.c
Not every test system has an `eth0` interface.
=> sa: lookup ifname for IPv6 link local scope interface

src/sipsess.c
replace pre-encoded SDP by sipsess_desc_handler() for INVITE
The sipsess_desc_handler() updates the laddr of the SDP session and encodes
the SDP just before the SIP INVITE is sent.
=> set sdp laddr to SIP src address

.github/workflows/all.yml, .github/workflows/build.yml, CMakeLists.txt
we should try to migrate all build scripts and projects
from make to cmake.
example projects:
- baresip-win32
- baresip-android
- baresip-ios
=> migrate to CMake for github workflows

src/jbuf.c
- jbuf: adaptive mode only handles re-order failures
- jbuf: test also out of order packets
=> aubuf adaptive jitter buffer

src/aubuf.c
A started flag was added to aubuf in order to avoid overruns before
the reading starts.
Relates to https://github.com/baresip/rem/pull/44
=> aubuf overruns on startup

.github/workflows/all.yml, src/bfcp.c, src/test.c, src/test.h
This test relies on and tests the updated BFCP APIs:
https://github.com/baresip/re/pull/411
=> bfcp: Add support for TCP transport for BFCP

src/dns.c
```
New defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)
** CID 1490848:  Memory - illegal accesses  (UNINIT)
/src/dns.c: 442 in test_dns_integration()
________________________________________________________________________________________________________
*** CID 1490848:  Memory - illegal accesses  (UNINIT)
/src/dns.c: 442 in test_dns_integration()
436     	/* --- Leave query open for cleanup test --- */
437     	err = dnsc_query(&q, data.dnsc, "test1.example.net", DNS_TYPE_A,
438     			 DNS_CLASS_IN, true, query_handler, &data);
439     	TEST_ERR(err);
440     
441     out:
>>>     CID 1490848:  Memory - illegal accesses  (UNINIT)
>>>     Using uninitialized value "data.dnsc" when calling "mem_deref".
442     	mem_deref(data.dnsc);
443     	mem_deref(srv);
444     
445 …
```
=> dns: init struct

CMakeLists.txt
This fixes issue when `OPENSSL_INCLUDE_DIR` is set `NOT-FOUND` by CMake
=> Don't fail on compilation when there no OpenSSL on target platform

src/sipreg.c
Tests should run without interfere with each other. Looks like on Github Actions runners share the same port range sometimes? So for tests we have to use dynamic ports only.
=> sipreg: use TEST_ERR and remove static port test

src/aubuf.c
While working on aubuf enhancements (get rid of malloc calls), I found a bug that is not catched by aubuf tests.
=> aubuf: refactor aubuf_auframe test

src/odict.c
Fixes a bug on Alpine/S390x which is 64-bit Big Endian architecture
=> odict: use correct union field (boolean)

src/tls.c
NOTE: made the test a bit flexible, so that it can handle old and new versions of re.
=> tls: remove some warnings

src/http.c, src/test.c, src/test.h
http: add test for set http and dns conf
test: disable test_dns_cache_http_integration because of mem leak segv on dns set conf
=> dnsc get conf and skip hash alloc without hash size changes

src/tls.c
The flag that indicates that the local TCP server to remote TCP client
connection was established has to be reset to false if the TCP connection is
closed.
Was found during working on: https://github.com/baresip/re/pull/607
=> tls: missing reset of TCP connection established flag

CMakeLists.txt, src/sa.c, src/test.c, src/test.h, src/unixsock.c
depends on https://github.com/baresip/re/pull/600
=> sa,unixsock: add unix domain socket support

src/sipsess.c, src/test.c, src/test.h
Refactoring of PRACK related tests to only call `re_cancel()` once per test and remove code duplication.
=> PRACK refactoring

src/sipsess.c
Refactor test to first unsuccesfully try to send answer, then send answer on PRACK received and close everything cleanly on established.
Fixes #176.
=> sipsess: fix 100rel_answer_not_allowed
